build-SharedLayer:
	./build-layer.sh

build-DataLambda:
	cp -r data $(ARTIFACTS_DIR)

build-TranscribeLambda:
	cp -r transcribe $(ARTIFACTS_DIR)

build-EnhanceLambda:
	cp -r enhance $(ARTIFACTS_DIR)

build-StoreLambda:
	cp -r store $(ARTIFACTS_DIR)