AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Metis Microservices

Globals:
  Function:
    Timeout: 900
    Runtime: python3.9

Resources:
  STTHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: stt-handler/
      Handler: app.lambda_handler
      Environment:
        Variables:
          PYTHONPATH: ./
          AUDIO_UPLOADS_BUCKET: !Ref AudioUploadsBucket
          TRANSCRIPTION_OUTPUT_BUCKET: !Ref TranscriptionOutputBucket
          STT_WORKFLOW_ARN: !Ref STTWorkflowArn
      Policies:
        - StepFunctionsExecutionPolicy:
            StateMachineName: !Ref STTWorkflowArn
        - S3WritePolicy:
            BucketName: !Ref AudioUploadsBucket
        - S3ReadPolicy:
            BucketName: !Ref TranscriptionOutputBucket
        - Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
            Resource:
              - !Sub "arn:aws:s3:::${AudioUploadsBucket}"
              - !Sub "arn:aws:s3:::${AudioUploadsBucket}/*"
              - !Sub "arn:aws:s3:::${TranscriptionOutputBucket}"
              - !Sub "arn:aws:s3:::${TranscriptionOutputBucket}/*"
        - Statement:
          - Effect: Allow
            Action:
              - transcribe:GetTranscriptionJob
              - transcribe:ListTranscriptionJobs
              - transcribe:StartTranscriptionJob
              - transcribe:DeleteTranscriptionJob
            Resource: "*"
    Metadata:
      BuildMethod: python3.9

  STTHandlerFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !Ref STTHandlerFunction
      AuthType: NONE
      Cors:
        AllowCredentials: false
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET
          - POST
        AllowHeaders:
          - Content-Type

  STTHandlerFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref STTHandlerFunction
      Action: lambda:InvokeFunctionUrl
      Principal: '*'
      FunctionUrlAuthType: NONE

Parameters:
  AudioUploadsBucket:
    Type: String
    Description: Name of the S3 bucket for audio uploads
  TranscriptionOutputBucket:
    Type: String
    Description: Name of the S3 bucket for transcription outputs
  STTWorkflowArn:
    Type: String
    Description: ARN of the STT Workflow State Machine

Outputs:
  STTHandlerFunctionUrl:
    Description: "STT Handler Function URL"
    Value: !GetAtt STTHandlerFunctionUrl.FunctionUrl